---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-account-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-account-example
  template:
    spec:
      serviceAccountName: service-account-example
      containers:
        - name: service-account-example
          image: larsks/service-account-example:20200922-02
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-account-example
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-account-example
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: service-account-example
spec:
  port:
    targetPort: 8080-8080
  tls:
    termination: edge
  to:
    name: service-account-example
